name:                hspec-golden-tutorial
version:             0.1.0.0
github:              "stackbuilders/tutorials/tree/tutorials/tutorials/haskell/hspec-golden-test-tutorial/code"
license:              MIT 
author:              "Stack Builders"
maintainer:          "jguerra@stackbuilders.com"
copyright:           "2019 Stack Builders"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/githubuser/hspec-golden-tests#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- bytestring
- blaze-html

library:
  source-dirs: src

executables:
  hspec-golden-tutorial-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec-golden-tutorial

tests:
  hspec-golden-tutorial-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec-golden-tutorial
    - hspec
    - hspec-golden
