name:                hspec-golden-tests
version:             0.1.0.0
github:              "githubuser/hspec-golden-tests"
license:              MIT 
author:              "Stack Builders"
maintainer:          "jguerra@stackbuilders.com"
copyright:           "2019 Stack Builders"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hspec-golden-tests#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- text
- bytestring
- blaze-html

library:
  source-dirs: src

executables:
  hspec-golden-tests-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec-golden-tests

tests:
  hspec-golden-tests-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec-golden-tests
    - hspec
    - hspec-golden
